.TH xgrep 1 "17 July 2007"
.LO 1
.SH NAME
xgrep \(hy search content of an XML file
.SH SYNOPSIS
.B xgrep
[\fB\-h\fR] [\fB\-v\fR] [\fB\-p\fR] [\fB\-c\fR \fIcatalog\-file\fR]
[\fB\-x\fR \fIxpath\fR] [\fB\-s\fR \fIstring\fR] ... [\fB\-s\fR
\fIstring\fR] [\fIinfile\fR] [\fIinfile\fR] ...
.SH DESCRIPTION
\fIxgrep\fP provides facilities for searching content in XML files. The search
is specified either as an XPath via the \fB\-x\fR flag, or a custom
syntax including extended regular expressions via the \fB\-s\fR flag.
Multiple input files may be specified; if none are provided, input is
read from stdin.
.SH OPTIONS
.l
\fIxgrep\fP accepts the following options:
.TP 8
.B  \-x \fIxpath\fR
An XPath specification of the elements of interest.
.TP 8
.B  \-s \fIstring\fR
A custom string format specifying the elements of interest. The string
format is
\fIbase\-element\fR:\fIelement\fR/\fIregex\fR/,\fIelement\fR/\fIregex\fR/,...
where \fIbase\-element\fR is the name of the elements within which a
match should be attempted, the match succeeding if, for each
\fIelement\fR/\fIregex\fR/ pair, the content of an element of that
name is matched by the corresponding regex. If multiple \fB\-s\fR flags
are specified, a match by any one of them is returned.
.TP 8
.B  \-c \fIcatalog\-file\fR
Use the specified catalog file instead of the default.
.TP 8
.B  \-p
Regular expressions use Perl syntax as implemented in the PCRE
library. (This option only available when xgrep has been linked with
the PCRE library.)
.TP 8
.B  \-h
Display usage information
.TP 8
.B  \-v
Display version information
.SH EXAMPLES
Consider an XML format, for personnel information, in which each
person element has descendant elements called name and hiredate. To
find all person elements with "Smith" in the content of the name
element and "2000" in the content of the hiredate element, do:
.PP
.Vb 1
\&    xgrep \-s 'person:name/Smith/,hiredate/2000/' a.xml b.xml
.Ve
.SH "SEE ALSO"
.BR regex (7),
.BR pcre (3), 
.BR xmllint (1)
.SH AUTHOR
Brendt Wohlberg <software@wohlberg.net>
